host: "127.0.0.1"
port: 8080
max_workers: 10
mounted_directories:
  - path: "/static"
    directory: "/home/bilb/Desktop/studia/sem5/PSI/http-server-psi-z33/src/funnel"
  - path: "/uploads"
    directory: "/home/bilb/Desktop/studia/sem5/PSI/http-server-psi-z33/examples"
